---
- name: "update apt packages."
  become: yes
  apt:
    update_cache: yes

- name: "upgrade packages"
  become: yes
  apt:
    upgrade: yes

- name: Extract artifact.tar.gz into the EC2 instance
  unarchive:  
    src: artifact.tar.gz  
    dest: /backend

- name: Executing Node
  shell: |
    cd backend
    npm install
    pm2 stop default
    pm2 start npm -- start